image: microsoft/dotnet:latest

stages:
  - build
  - test

before_script:
  - dotnet restore -s https://www.myget.org/F/s2/ -s https://api.nuget.org/v3/index.json

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  script:
    - echo "$GCP_CREDENTIALS" > "$(pwd)/service_credentials.json"
    - dotnet build
    - dotnet test
