image: microsoft/dotnet:latest

stages:
  - build
  - test

before_script:
  - dotnet restore -s https://www.myget.org/F/s2/ -s https://api.nuget.org/v3/index.json

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  script:
    - dotnet build
    - echo '$GCP_CREDENTIALS' > "GoogleBigQuerySupplyCollectorTests/bin/Debug/netcoreapp2.2/service-credentials.json"
    - cat GoogleBigQuerySupplyCollectorTests/bin/Debug/netcoreapp2.2/service-credentials.json
    - dotnet test
